In [20]:

import pandas as pd 
import numpy as np

In [21]:
df = pd.read_csv('pns2019.csv')

In [22]:
fields,columns = df.shape
print(f'SHAPE\nColunas {columns}\nLinhas {fields}')

SHAPE
Colunas 1087
Linhas 293726

In [23]:
df.info(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293726 entries, 0 to 293725
Data columns (total 1087 columns):
 #     Column     Dtype
---    ------     -----
 0     V0001      int64
 1     V0024      int64
 2     UPA_PNS    int64
 3     V0006_PNS  int64
 4     V0015      int64
 5     V0020      int64
 6     V0022      float64
 7     V0026      int64
 8     V0031      int64
 9     V0025A     float64
 10    V0025B     float64
 11    A001       float64
 12    A002010    float64
 13    A003010    float64
 14    A004010    float64
 15    A01001     float64
 16    A011       float64
 17    A005010    float64
 18    A005012    float64
 19    A00601     float64
 20    A009010    float64
 21    A01401     float64
 22    A01402     float64
 23    A01403     float64
 24    A01501     float64
 25    A016010    float64
 26    A018011    float64
 27    A018012    float64
 28    A018013    float64
 29    A018014    float64
 30    A018015    float64
 31    A018016    float64
 32    A018017    float64
 33    A018018    float64
 34    A018019    float64
 35    A018020    float64
 36    A018021    float64
 37    A018022    float64
 38    A018023    float64
 39    A018024    float64
 40    A018025    float64
 41    A018026    float64
 42    A018027    float64
 43    A018028    float64
 44    A01901     float64
 45    A02101     float64
 46    A02102     float64
 47    A02201     float64
 48    A02305     float64
 49    A02306     float64
 50    A02307     float64
 51    A02308     float64
 52    A02401     float64
 53    A02402     float64
 54    B001       float64
 55    B002       float64
 56    B003       float64
 57    B004       float64
 58    C001       float64
 59    C00301     float64
 60    C004       float64
 61    C006       float64
 62    C00701     float64
 63    C00702     float64
 64    C00703     float64
 65    C008       float64
 66    C009       float64
 67    C01001     float64
 68    C010010    float64
 69    C013       float64
 70    C014       float64
 71    C015       float64
 72    C016       float64
 73    C017       float64
 74    C018       float64
 75    C01801     float64
 76    C011       float64
 77    C012       float64
 78    D001       float64
 79    D00201     float64
 80    D00202     float64
 81    D00301     float64
 82    D00501     float64
 83    D006       float64
 84    D00601     float64
 85    D007       float64
 86    D008       float64
 87    D00901     float64
 88    D010       float64
 89    D01101     float64
 90    D01201     float64
 91    D01301     float64
 92    D01302     float64
 93    D01303     float64
 94    D014       float64
 95    D015       float64
 96    E001       float64
 97    E002       float64
 98    E003       float64
 99    E004       float64
 100   E005       float64
 101   E006011    float64
 102   E008       float64
 103   E010010    float64
 104   E010011    float64
 105   E010012    float64
 106   E010013    float64
 107   E011       float64
 108   E01201     float64
 109   E01401     float64
 110   E014011    float64
 111   E01402     float64
 112   E01403     float64
 113   E01501     float64
 114   E01601     float64
 115   E01602     float64
 116   E01603     float64
 117   E01604     float64
 118   E01605     float64
 119   E017       float64
 120   E01801     float64
 121   E01802     float64
 122   E01803     float64
 123   E01804     float64
 124   E01805     float64
 125   E019       float64
 126   E022       float64
 127   E023011    float64
 128   E024011    float64
 129   E02402     float64
 130   E024021    float64
 131   E025       float64
 132   E02501     float64
 133   E02502     float64
 134   E02503     float64
 135   E026       float64
 136   E02601     float64
 137   E02801     float64
 138   E02802     float64
 139   E02803     float64
 140   E02804     float64
 141   E02805     float64
 142   E02806     float64
 143   E030       float64
 144   E03101     float64
 145   E03102     float64
 146   E03103     float64
 147   E03104     float64
 148   E03105     float64
 149   E03106     float64
 150   E03107     float64
 151   E03108     float64
 152   E032       float64
 153   E033       float64
 154   E027       float64
 155   F001011    float64
 156   F001021    float64
 157   F007011    float64
 158   F007021    float64
 159   F008011    float64
 160   F008021    float64
 161   VDF001     float64
 162   VDF00102   float64
 163   F016       float64
 164   G033       float64
 165   G034       float64
 166   G035       float64
 167   G036       float64
 168   G038       float64
 169   G039       float64
 170   G040       float64
 171   G041       float64
 172   G042       float64
 173   G044       float64
 174   G046       float64
 175   G047       float64
 176   G048       float64
 177   G049       float64
 178   G050       float64
 179   G051       float64
 180   G052       float64
 181   G053       float64
 182   G054       float64
 183   G055       float64
 184   G057       float64
 185   G058       float64
 186   G05801     float64
 187   G059       float64
 188   G060       float64
 189   G061       float64
 190   G062       float64
 191   G063       float64
 192   G064       float64
 193   G065       float64
 194   G066       float64
 195   G067       float64
 196   G068       float64
 197   G070       float64
 198   G071       float64
 199   G072       float64
 200   G073       float64
 201   G074       float64
 202   G075       float64
 203   G076       float64
 204   G077       float64
 205   G079       float64
 206   G080       float64
 207   G081       float64
 208   G082       float64
 209   G083       float64
 210   G084       float64
 211   G085       float64
 212   G086       float64
 213   G032       float64
 214   I00101     float64
 215   I00102     float64
 216   I001021    float64
 217   I00103     float64
 218   I001031    float64
 219   I005       float64
 220   I006       float64
 221   I004       float64
 222   I00401     float64
 223   I00402     float64
 224   I00403     float64
 225   I00404     float64
 226   I010010    float64
 227   I012       float64
 228   J001       float64
 229   J00101     float64
 230   J002       float64
 231   J003       float64
 232   J00402     float64
 233   J00404     float64
 234   J005       float64
 235   J006       float64
 236   J007       float64
 237   J00801     float64
 238   J009       float64
 239   J01002     float64
 240   J01101     float64
 241   J012       float64
 242   J01301     float64
 243   J014       float64
 244   J01502     float64
 245   J01602     float64
 246   J01701     float64
 247   J01802     float64
 248   J019       float64
 249   J02002     float64
 250   J021       float64
 251   J022010    float64
 252   J023       float64
 253   J024       float64
 254   J025       float64
 255   J026       float64
 256   J02702     float64
 257   J02901     float64
 258   J03001     float64
 259   J03102     float64
 260   J032       float64
 261   J03301     float64
 262   J034       float64
 263   J035       float64
 264   J03602     float64
 265   J037       float64
 266   J038       float64
 267   J039       float64
 268   J04001     float64
 269   J04002     float64
 270   J041       float64
 271   J042       float64
 272   J043       float64
 273   J044       float64
 274   J046       float64
 275   J047       float64
 276   J048       float64
 277   J049       float64
 278   J051       float64
 279   J052       float64
 280   J05301     float64
 281   J05402     float64
 282   J05403     float64
 283   J05404     float64
 284   J05405     float64
 285   J05406     float64
 286   J05407     float64
 287   J05408     float64
 288   J05409     float64
 289   J054010    float64
 290   J056       float64
 291   J057       float64
 292   J060       float64
 293   K001       float64
 294   K004       float64
 295   K007       float64
 296   K010       float64
 297   K013       float64
 298   K016       float64
 299   K019       float64
 300   K01901     float64
 301   K02001     float64
 302   K02101     float64
 303   K02102     float64
 304   K022       float64
 305   K025       float64
 306   K028       float64
 307   K031       float64
 308   K034       float64
 309   K03401     float64
 310   K03501     float64
 311   K03601     float64
 312   K03602     float64
 313   K04301     float64
 314   K04302     float64
 315   K04401     float64
 316   K045       float64
 317   K046       float64
 318   K047       float64
 319   K048       float64
 320   K050       float64
 321   K051       float64
 322   K052       float64
 323   K05302     float64
 324   K05401     float64
 325   K05402     float64
 326   k055       float64
 327   K05601     float64
 328   K05602     float64
 329   K062       float64
 330   L01701     float64
 331   L01702     float64
 332   L01703     float64
 333   L01704     float64
 334   L01705     float64
 335   L01706     float64
 336   L01707     float64
 337   L01708     float64
 338   L01709     float64
 339   L01710     float64
 340   L01711     float64
 341   L01712     float64
 342   L01713     float64
 343   L01714     float64
 344   L01715     float64
 345   L01716     float64
 346   L018       float64
 347   L019       float64
 348   L021       float64
 349   L022       float64
 350   L023       float64
 351   L024       float64
 352   L025       float64
 353   L026       float64
 354   L027       float64
 355   L028       float64
 356   L029       float64
 357   L030       float64
 358   L031       float64
 359   L032       float64
 360   L033       float64
 361   L034       float64
 362   L035       float64
 363   L036       float64
 364   L037       float64
 365   L038       float64
 366   L039       float64
 367   L040       float64
 368   L042       float64
 369   M001       float64
 370   M002       float64
 371   M00203     float64
 372   M00302     float64
 373   M00303     float64
 374   M00401     float64
 375   M00402     float64
 376   M005010    float64
 377   M005011    float64
 378   M00601     float64
 379   M007       float64
 380   M008       float64
 381   M009       float64
 382   M01001     float64
 383   M011011    float64
 384   M011021    float64
 385   M011031    float64
 386   M011041    float64
 387   M011051    float64
 388   M011061    float64
 389   M011071    float64
 390   M01401     float64
 391   M01501     float64
 392   M01601     float64
 393   M01701     float64
 394   M01801     float64
 395   M01901     float64
 396   N001       float64
 397   N00101     float64
 398   N004       float64
 399   N005       float64
 400   N006       float64
 401   N00701     float64
 402   N008       float64
 403   N010       float64
 404   N011       float64
 405   N012       float64
 406   N013       float64
 407   N014       float64
 408   N015       float64
 409   N016       float64
 410   N017       float64
 411   N018       float64
 412   O00101     float64
 413   O00401     float64
 414   O00402     float64
 415   O00501     float64
 416   O00201     float64
 417   O00701     float64
 418   O00801     float64
 419   O00802     float64
 420   O00803     float64
 421   O009       float64
 422   O00901     float64
 423   O010       float64
 424   O01102     float64
 425   O01401     float64
 426   O01501     float64
 427   O01602     float64
 428   O01702     float64
 429   O019       float64
 430   O02001     float64
 431   O021       float64
 432   O02101     float64
 433   O02201     float64
 434   O023       float64
 435   O02401     float64
 436   P00102     float64
 437   P00103     float64
 438   P00104     float64
 439   P00201     float64
 440   P00402     float64
 441   P00403     float64
 442   P00404     float64
 443   P00405     float64
 444   P005       float64
 445   P00601     float64
 446   P00602     float64
 447   P00603     float64
 448   P00604     float64
 449   P00605     float64
 450   P00607     float64
 451   P00608     float64
 452   P00609     float64
 453   P00610     float64
 454   P00611     float64
 455   P00612     float64
 456   P00613     float64
 457   P00614     float64
 458   P00615     float64
 459   P00616     float64
 460   P00617     float64
 461   P00618     float64
 462   P00619     float64
 463   P00620     float64
 464   P00621     float64
 465   P00622     float64
 466   P00623     float64
 467   P006       float64
 468   P00901     float64
 469   P01001     float64
 470   P01101     float64
 471   P013       float64
 472   P015       float64
 473   P02001     float64
 474   P02101     float64
 475   P01601     float64
 476   P018       float64
 477   P019       float64
 478   P02002     float64
 479   P02102     float64
 480   P023       float64
 481   P02401     float64
 482   P02501     float64
 483   P02602     float64
 484   P02601     float64
 485   P027       float64
 486   P02801     float64
 487   P029       float64
 488   P03201     float64
 489   P03202     float64
 490   P03001     float64
 491   P03301     float64
 492   P03302     float64
 493   P03303     float64
 494   P034       float64
 495   P035       float64
 496   P03701     float64
 497   P03702     float64
 498   P036       float64
 499   P038       float64
 500   P039       float64
 501   P03904     float64
 502   P03905     float64
 503   P03906     float64
 504   P040       float64
 505   P04001     float64
 506   P04101     float64
 507   P04102     float64
 508   P042       float64
 509   P04301     float64
 510   P04302     float64
 511   P044       float64
 512   P04401     float64
 513   P04405     float64
 514   P04406     float64
 515   P04501     float64
 516   P04502     float64
 517   P046       float64
 518   P04701     float64
 519   P04801     float64
 520   P04902     float64
 521   P050       float64
 522   P051       float64
 523   P052       float64
 524   P053       float64
 525   P05401     float64
 526   P05402     float64
 527   P05403     float64
 528   P05404     float64
 529   P05405     float64
 530   P05406     float64
 531   P05407     float64
 532   P05408     float64
 533   P05409     float64
 534   P05410     float64
 535   P05411     float64
 536   P05412     float64
 537   P05413     float64
 538   P05414     float64
 539   P05415     float64
 540   P05416     float64
 541   P05417     float64
 542   P05418     float64
 543   P05419     float64
 544   P05421     float64
 545   P05422     float64
 546   P055       float64
 547   P056       float64
 548   P05601     float64
 549   P05602     float64
 550   P05603     float64
 551   P05604     float64
 552   P05605     float64
 553   P057       float64
 554   P058       float64
 555   P05801     float64
 556   P05802     float64
 557   P05901     float64
 558   P05902     float64
 559   P05903     float64
 560   P05904     float64
 561   P05905     float64
 562   P05906     float64
 563   P060       float64
 564   P06101     float64
 565   P06102     float64
 566   P06103     float64
 567   P06104     float64
 568   P06105     float64
 569   P06106     float64
 570   P06302     float64
 571   P067       float64
 572   P06701     float64
 573   P068       float64
 574   P069       float64
 575   P06901     float64
 576   P07004     float64
 577   P07005     float64
 578   P07006     float64
 579   P07007     float64
 580   P07101     float64
 581   P07201     float64
 582   Q00101     float64
 583   Q00201     float64
 584   Q00202     float64
 585   Q003       float64
 586   Q00401     float64
 587   Q00502     float64
 588   Q00503     float64
 589   Q00601     float64
 590   Q00602     float64
 591   Q00801     float64
 592   Q009       float64
 593   Q010       float64
 594   Q01101     float64
 595   Q01202     float64
 596   Q014       float64
 597   Q015       float64
 598   Q016       float64
 599   Q017       float64
 600   Q018010    float64
 601   Q018011    float64
 602   Q018012    float64
 603   Q018013    float64
 604   Q018014    float64
 605   Q018015    float64
 606   Q018016    float64
 607   Q018017    float64
 608   Q01910     float64
 609   Q019101    float64
 610   Q01911     float64
 611   Q019111    float64
 612   Q01912     float64
 613   Q019121    float64
 614   Q01913     float64
 615   Q019131    float64
 616   Q022       float64
 617   Q02301     float64
 618   Q026       float64
 619   Q02701     float64
 620   Q028       float64
 621   Q02901     float64
 622   Q03001     float64
 623   Q03002     float64
 624   Q031       float64
 625   Q03201     float64
 626   Q03302     float64
 627   Q03303     float64
 628   Q03403     float64
 629   Q03404     float64
 630   Q03601     float64
 631   Q03701     float64
 632   Q03801     float64
 633   Q03802     float64
 634   Q03803     float64
 635   Q03804     float64
 636   Q03805     float64
 637   Q03806     float64
 638   Q03807     float64
 639   Q03901     float64
 640   Q04002     float64
 641   Q042       float64
 642   Q043       float64
 643   Q044       float64
 644   Q045       float64
 645   Q046011    float64
 646   Q046012    float64
 647   Q046013    float64
 648   Q046014    float64
 649   Q046015    float64
 650   Q046016    float64
 651   Q046017    float64
 652   Q046018    float64
 653   Q046019    float64
 654   Q046020    float64
 655   Q046021    float64
 656   Q04707     float64
 657   Q047071    float64
 658   Q04708     float64
 659   Q047081    float64
 660   Q04709     float64
 661   Q047091    float64
 662   Q04710     float64
 663   Q047101    float64
 664   Q04711     float64
 665   Q047111    float64
 666   Q050       float64
 667   Q05101     float64
 668   Q05301     float64
 669   Q05401     float64
 670   Q055011    float64
 671   Q055012    float64
 672   Q055013    float64
 673   Q055014    float64
 674   Q055015    float64
 675   Q055016    float64
 676   Q056       float64
 677   Q05701     float64
 678   Q058       float64
 679   Q05901     float64
 680   Q060       float64
 681   Q061       float64
 682   Q06207     float64
 683   Q06208     float64
 684   Q06209     float64
 685   Q06210     float64
 686   Q06211     float64
 687   Q06212     float64
 688   Q06306     float64
 689   Q06307     float64
 690   Q06308     float64
 691   Q06309     float64
 692   Q06310     float64
 693   Q06311     float64
 694   Q064       float64
 695   Q06506     float64
 696   Q06507     float64
 697   Q06508     float64
 698   Q06509     float64
 699   Q06601     float64
 700   Q067       float64
 701   Q068       float64
 702   Q070       float64
 703   Q07208     float64
 704   Q07209     float64
 705   Q07210     float64
 706   Q07211     float64
 707   Q07212     float64
 708   Q07213     float64
 709   Q073       float64
 710   Q074       float64
 711   Q075       float64
 712   Q076       float64
 713   Q07601     float64
 714   Q07704     float64
 715   Q07705     float64
 716   Q07706     float64
 717   Q07707     float64
 718   Q07708     float64
 719   Q07709     float64
 720   Q07710     float64
 721   Q07711     float64
 722   Q078       float64
 723   Q079       float64
 724   Q080       float64
 725   Q08107     float64
 726   Q08108     float64
 727   Q08109     float64
 728   Q08110     float64
 729   Q08111     float64
 730   Q082       float64
 731   Q083       float64
 732   Q084       float64
 733   Q085       float64
 734   Q08607     float64
 735   Q08608     float64
 736   Q08609     float64
 737   Q08610     float64
 738   Q08611     float64
 739   Q087       float64
 740   Q088       float64
 741   Q08901     float64
 742   Q09007     float64
 743   Q09008     float64
 744   Q09009     float64
 745   Q09010     float64
 746   Q09011     float64
 747   Q091       float64
 748   Q092       float64
 749   Q09201     float64
 750   Q09202     float64
 751   Q09301     float64
 752   Q094       float64
 753   Q09502     float64
 754   Q09605     float64
 755   Q09606     float64
 756   Q09607     float64
 757   Q098       float64
 758   Q100       float64
 759   Q10101     float64
 760   Q10202     float64
 761   Q104       float64
 762   Q105       float64

In [24]:
df.describe()

,V0001,V0024,UPA_PNS,V0006_PNS,V0015,V0020,V0022,V0026,V0031,V0025A,...,VDE002,VDE014,VDF002,VDF003,VDF004,VDL001,VDM001,VDP001,VDR001,VDDATA
count,293726.000000,2.937260e+05,2.937260e+05,293726.000000,293726.000000,293726.0,279382.000000,293726.000000,293726.000000,279382.000000,...,136595.000000,124399.000000,279210.000000,279210.000000,279210.000000,6632.000000,44462.000000,8149.000000,17376.000000,293726.0
mean,28.844716,2.916156e+06,2.885244e+08,7.408667,1.170686,2019.0,3.738602,1.236843,2.589492,2.214520,...,1.089286,5.416048,4095.075101,1314.001046,3.197174,15.669783,2.182763,1.364216,4.054500,20210825.0
std,11.762108,1.174962e+06,1.176431e+08,4.124520,0.892174,0.0,1.727899,0.425146,1.387005,3.511653,...,0.285157,3.199733,6685.171169,2307.681908,1.504282,13.169331,1.084318,0.509002,1.923417,0.0
min,11.000000,1.110011e+06,1.100000e+08,1.000000,1.000000,2019.0,1.000000,1.000000,1.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,20210825.0
25%,21.000000,2.152011e+06,2.100481e+08,4.000000,1.000000,2019.0,3.000000,1.000000,1.000000,0.000000,...,1.000000,3.000000,1371.000000,399.000000,2.000000,8.000000,1.000000,1.000000,2.000000,20210825.0
50%,27.000000,2.752010e+06,2.700277e+08,7.000000,1.000000,2019.0,4.000000,1.000000,2.000000,1.000000,...,1.000000,5.000000,2498.000000,760.000000,3.000000,14.000000,2.000000,1.000000,5.000000,20210825.0
75%,35.000000,3.521020e+06,3.503672e+08,11.000000,1.000000,2019.0,5.000000,1.000000,4.000000,1.000000,...,1.000000,8.000000,4500.000000,1397.000000,4.000000,21.000000,3.000000,2.000000,5.000000,20210825.0
max,53.000000,5.310220e+06,5.300511e+08,18.000000,12.000000,2019.0,23.000000,2.000000,4.000000,9.000000,...,2.000000,12.000000,644998.000000,203196.000000,7.000000,99.000000,4.000000,3.000000,9.000000,20210825.0

In [25]:
# Selecionar apenas pessoas com toc e entre 30 e 60
df_toc = df[(df["Q11009"] == 1) & (df["C008"] > 30) & (df["C008"] <= 60)]

## Colunas das doenças
    |  Num Coluna  |   Doença     |
    |-----------------------------|
    |Q00201 | hipertensão arterial|
    |Q03001| diabetes |
    |Q060 |colesterol alto|
    |Q06306 | doença do coração|
    |Q068 |AVC |
    |Q074 |asma |
    |Q079 |artrite |
    |Q088 |DORT |
    |Q092 |depressão |
    |Q11006 | doença mental |
    |Q11604 | outra doença crônica | 
    |Q120 | câncer |
    |Q128  | outra doença crônica (física ou mental)|

In [29]:

cols = ["Q00201","Q03001","Q060","Q06306","Q068",
        "Q074","Q079","Q088","Q092","Q11006","Q11604","Q120","Q128"]

df_bem = df[df[cols].eq(2).all(axis=1)]
df_bem = df_bem[(df_bem["C008"] > 30) & (df_bem["C008"] <= 60)]

In [30]:
df = pd.concat([df_toc, df_bem], ignore_index=True)
df

,V0001,V0024,UPA_PNS,V0006_PNS,V0015,V0020,V0022,V0026,V0031,V0025A,...,VDE002,VDE014,VDF002,VDF003,VDF004,VDL001,VDM001,VDP001,VDR001,VDDATA
0,11,1110011,110005539,5,1,2019,10.0,1,1,1.0,...,NaN,NaN,8994.0,899.0,3.0,NaN,NaN,NaN,NaN,20210825
1,11,1110012,110017590,6,1,2019,2.0,1,1,1.0,...,1.0,2.0,6100.0,3050.0,6.0,NaN,NaN,NaN,NaN,20210825
2,11,1152011,110020167,8,1,2019,1.0,1,4,1.0,...,NaN,NaN,998.0,998.0,3.0,NaN,NaN,NaN,NaN,20210825
3,11,1152013,110017035,15,1,2019,3.0,1,4,1.0,...,1.0,8.0,1300.0,433.0,2.0,NaN,3.0,NaN,4.0,20210825
4,12,1210010,120002727,14,1,2019,5.0,1,1,1.0,...,1.0,8.0,6000.0,1500.0,4.0,NaN,2.0,NaN,NaN,20210825
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22460,53,5310220,530041727,4,1,2019,2.0,2,1,1.0,...,1.0,1.0,2000.0,1000.0,4.0,NaN,1.0,NaN,NaN,20210825
22461,53,5310220,530041727,5,1,2019,3.0,2,1,1.0,...,1.0,1.0,2820.0,940.0,3.0,NaN,1.0,NaN,NaN,20210825
22462,53,5310220,530044434,1,1,2019,2.0,2,1,1.0,...,1.0,9.0,5500.0,2750.0,5.0,NaN,3.0,NaN,NaN,20210825
22463,53,5310220,530044434,2,1,2019,1.0,2,1,1.0,...,1.0,5.0,7200.0,7200.0,7.0,NaN,3.0,NaN,NaN,20210825
22464,53,5310220,530044434,11,1,2019,4.0,2,1,1.0,...,NaN,NaN,1497.0,374.0,2.0,NaN,NaN,NaN,NaN,20210825

# Colunas Interresantes

V0001 Unidade da Federação
C006 Sexo
C008 Idade do morador na data de referência
P00104 Peso - Final (em kg)
P00404 Altura - Final (em cm)
P01001 Em geral, o(a) Sr(a) costuma comer esse tipo de verdura ou legume
P01101 Em quantos dias da semana o(a) Sr(a) costuma comer carne vermelha (boi, porco, cabrito, bode, ovelha etc.)? 
P013 Em quantos dias da semana o(a) Sr(a) costuma comer frango/galinha?
P02001	Suco de caixinha/lata/pó
P01601	Suco natural
P018	Frutas
P02002	Refrigerante
P023	Leite
P02501	Doces
P02602	Lanches rapidos
P027	bebidas alcoólicas
P03201	Cinco ou mais doses de bebida alcoólica
P02801	Frequência diária de bebidas alcoólicas (p027)
P02101	Tipo de suco industrializado (p02001)
P02102	Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante (p02002)
P02401	Tipo leite 
P035 Quantos dias por semana o(a) Sr(a) costuma  (costumava)praticar exercício físico ou esporte?
P050 Atualmente, o(a) Sr(a) fuma algum produto do tabaco?